### ISSUE TITLE
Watermark Overlay on Image

### ISSUE THREAD

**Issue by Ahury** [filippotoso/pdf-watermarker#11]
It's work perfectly with only-text PDF File, but there's a problem when it contains image.

the Watermark Text always go under the image like this :

![Screenshot 2024-05-30 141621](https://github.com/filippotoso/pdf-watermarker/assets/171226437/61d7051b-c30e-48ed-9142-35709eaec00c)

Here is my code : 

`use FilippoToso\PdfWatermarker\Facades\TextWatermarker;`
`use FilippoToso\PdfWatermarker\Support\Position;`

`TextWatermarker::input(public_path().'testing.pdf')`
`            ->asBackground()`
`            ->text($request->textraw)`
`            ->angle(25)`
`            ->font(public_path().'/font/OpenSans-Regular.ttf')`
`            ->size('200')`
`            ->color('#CC00007F')`
`            ->resolution(300)`
`            ->stream('example.pdf');`

any suggestions what's wrong ?

**Comment by filippotoso** [comment]
You have told it to place thw watermark as background.

```
->asBackground()
```
