### ISSUE TITLE
Download method not working on Livewire

### ISSUE THREAD

**Issue by madurapa** [filippotoso/pdf-watermarker#12]
So you have to use the `save()` or `stream()` methods from the package and then use Livewire `download()` or `streamDownload()` to be able to download when you are using Livewire.

More information on https://livewire.laravel.com/docs/downloads

Thanks for the package!

**Comment by filippotoso** [comment]
Try version 1.1.0

**Comment by madurapa** [comment]
Works like a charm! Thank you very much!
