### ISSUE TITLE
Multi

### ISSUE THREAD

**Issue by APTEMOH** [filippotoso/pdf-watermarker#3]
Hi!

Please help!

`use FilippoToso\PdfWatermarker\Support\Pdf;
use FilippoToso\PdfWatermarker\Watermarks\ImageWatermark;
use FilippoToso\PdfWatermarker\Watermarks\TextWatermark;
use FilippoToso\PdfWatermarker\PdfWatermarker;
use FilippoToso\PdfWatermarker\Support\Position;

// Specify path to the existing pdf
$pdf = new Pdf('cashback.pdf');
	
for ($i=1; $i <= 3; $i++) {
	
	if($i == 1){
		// Set the position of the watermark including optional X/Y offsets
		$position = new Position(Position::TOP_CENTER, -20, -20);
	}elseif($i == 2){
		// Set the position of the watermark including optional X/Y offsets
		$position = new Position(Position::MIDDLE_CENTER, -20, -20);
	}elseif($i == 3){
		// Set the position of the watermark including optional X/Y offsets
		$position = new Position(Position::BOTTOM_CENTER, -20, -20);
	}

	// Specify path to image. The image must have a 96 DPI resolution.
	//$watermark = new ImageWatermark('watermark.png'); 
	$watermark = new TextWatermark('watermark fuck', 'Verdana.ttf', 80, 10, '#c53c0aad'); 

	// Create a new watermarker
	$watermarker = new PDFWatermarker($pdf, $watermark); 

	// All possible positions can be found in Position::options
	$watermarker->setPosition($position);
	
	// Save the new PDF to its specified location
	$watermarker->save('output.pdf');
}`

Why don't work?

Thanks!

**Comment by filippotoso** [comment]
Please define "Why don't work?"

**Comment by APTEMOH** [comment]
> Please define "Why don't work?"

On output.pdf - onw watermark text

I want ten or 3 on my code example.

**Comment by APTEMOH** [comment]
Pls help!

**Comment by filippotoso** [comment]
You have to use temporary files if you want to watermark a file multiple times.

Copy  the source into a temporary file. Use it as bot input and output in the loop and then copy it in the final destination.
