### ISSUE TITLE
This PDF document is encrypted and cannot be processed with FPDI.

### ISSUE THREAD

**Issue by NALAWALAMURTUZA** [filippotoso/pdf-watermarker#4]
Please suggest how to resolve this issue.

![Screenshot (145)](https://github.com/filippotoso/pdf-watermarker/assets/8521122/1bf6f458-42f8-4fda-92ef-8c6eabbaf10a)

**Comment by filippotoso** [comment]
You  have to decrypt the PDF before processing it.

**Comment by NALAWALAMURTUZA** [comment]
@filippotoso i m used test.pdf file below is my file
[1698298617_bid.pdf](https://github.com/filippotoso/pdf-watermarker/files/13264376/1698298617_bid.pdf)

**Comment by NALAWALAMURTUZA** [comment]
or is there any way we can identify this is a secure pdf file?
@filippotoso

**Comment by filippotoso** [comment]
Just try/catch the exception
