### ISSUE TITLE
The specified font file is not valid

### ISSUE THREAD

**Issue by Unnicha** [filippotoso/pdf-watermarker#5]
just trying ->font('arial.ttf') and got this

![Screenshot 2024-01-02 104010](https://github.com/filippotoso/pdf-watermarker/assets/48424841/ff02b404-3305-4014-8587-91c9d3b6c5cd)

**Comment by filippotoso** [comment]
You must pass the full path of the font.

**Comment by Unnicha** [comment]
oh, so I need to include the font file manually?

**Comment by filippotoso** [comment]
If you need to use a resouce (ie. a font), you need that resource to be accessible from your PHP code.
